### ISSUE TITLE
Data arrives split in 1024 byte chunks instead of the whole frame

### ISSUE THREAD

**Issue by yiown** [feixuwu/UEWebsocket#16]
The OnReceivedData event delivers an FString with only 1024 bytes of the entire json.
Then it generates several events delivering the rest of the json in more and more 1024 bytes chunks.
These are not real events from the socket (not new frames) but just the data being pulled from the input side of the socket.  

I had to manually buffer the json until I had it all in the buffer so I could parse it and cast it to a data object.
BUT it is impossible to have the frame boundary and thus I have to preparse the curly braces to understand where the json starts and where it ends.  

It would be ideal to have the OnReceiveData deliver THE ENTIRE SOCKET FRAME DATA in one event.
This could be as simple and allowing the recv buffer size to be specified as a parameter.

Regards.

**Comment by feixuwu** [comment]
this should not happen, please confirm you did not send per 1024 bytes, check you send code, or you can use the demo project to do the test.

?? Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by yiown** [comment]
I have several clients in different languages, this is an exercise I created to teach restful services at the company. All of them work fine.
I have little time to touch your example but I guess if you use a big enough json you will get the same error.
Hope it helps.

**Comment by feixuwu** [comment]
Hi,
websocket is frame base, the plugin have a macro define the max data size,
#define MAX_ECHO_PAYLOAD 64*1024

So if you package size is more then 64*1024, you need change this macro to more big value, I guess this is the reason you get error?
Although websocket is frame base protocol, it’s a good practice to set the max package size to a reasonable value.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Fernando Farias <notifications@github.com>
发送时间: Sunday, July 8, 2018 8:29:39 AM
收件人: feixuwu/UEWebsocket
抄送: xufeiwu; State change
主题: Re: [feixuwu/UEWebsocket] Data arrives split in 1024 byte chunks instead of the whole frame (#16)


I have several clients in different languages, this is an exercise I created to teach restful services at the company. All of them work fine.
I have little time to touch your example but I guess if you use a big enough json you will get the same error.
Hope it helps.

―

**Comment by yiown** [comment]
Can you make this as a parameter ?
So we can change the buffer size from blueprints ?

**Comment by feixuwu** [comment]
I’m afraid this value can not change dynamic.
You can change this value in plugin code.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Fernando Farias <notifications@github.com>
发送时间: Sunday, July 8, 2018 8:39:50 AM
收件人: feixuwu/UEWebsocket
抄送: xufeiwu; State change
主题: Re: [feixuwu/UEWebsocket] Data arrives split in 1024 byte chunks instead of the whole frame (#16)


Can you make this as a parameter ?
So we can change the buffer size from blueprints ?

―

**Comment by yiown** [comment]
It may need a refactor...
I will try it when I have the time.
