### ISSUE TITLE
WS Connect Blueprint node doesn't accept localhost:8000 as host

### ISSUE THREAD

**Issue by michela** [feixuwu/UEWebsocket#18]
The WS Connect Blueprint node doesn't seems to accept port numbers e.g. localhost:8000 

Repro:
* ws://<FQHN>/ws/console?subscribe-broadcast&publish-broadcast

WORKS

* ws://localhost:8000/ws/console?subscribe-broadcast&publish-broadcast

DOESN"T CONNECT

**Comment by nsjames** [comment]
Indeed I'm seeing the same thing when adding `localhost:<PORT>`, which also seems to prevent **any** events from being fired even the connection error event.

**Comment by feixuwu** [comment]
I will check this problem this weekend, thank you guys very much

**Comment by anadin** [comment]
@feixuwu sorry to bug you but will you be able to look at this soon?

**Comment by feixuwu** [comment]
Maybe you can use 127.0.0.1 replace localhost, currently I’m too busy to check this problem.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: anadin <notifications@github.com>
发送时间: Sunday, August 19, 2018 9:58:13 AM
收件人: feixuwu/UEWebsocket
抄送: xufeiwu; Mention
主题: Re: [feixuwu/UEWebsocket] WS Connect Blueprint node doesn't accept localhost:8000 as host (#18)


@feixuwu<https://github.com/feixuwu> sorry to bug you but will you be able to look at this soon?

―

**Comment by feixuwu** [comment]
Hi, I test with localhost and the connect error event will fire, because of the error message is empty, so you may not see the error message.
But the connect error event is fired, please check it again, if you still have problem, please let me know.
Thanks very much!

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: anadin <notifications@github.com>
发送时间: Sunday, August 19, 2018 9:58:13 AM
收件人: feixuwu/UEWebsocket
抄送: xufeiwu; Mention
主题: Re: [feixuwu/UEWebsocket] WS Connect Blueprint node doesn't accept localhost:8000 as host (#18)


@feixuwu<https://github.com/feixuwu> sorry to bug you but will you be able to look at this soon?

―

**Comment by feixuwu** [comment]
with the demo server, you can easy to find it works on localhost too.
