### ISSUE TITLE
Issue connecting to wss

### ISSUE THREAD

**Issue by kgriffiths** [feixuwu/UEWebsocket#27]
Hi, I've been able to connect to a wss address for months using this plugin for UE. Then an issue started a couple days ago, where this plugin has been unable to connect (the handshake fails). The wss is a 3rd party API, and there aren't any issues with the API itself - I'm able to connect successfully with other types of clients, using identical authentication. 

There seems to be an issue with the handshake for this specific plugin. Digging into this, I believe this issue could involve the CA certs. I haven't actually used the CA folder as specified in this repo before (and it still connected well). Now I'm trying to use your included folder and still not having success connecting to the websocket.

Do you have any ideas what might be causing this? Does this plugin use CA certs from Windows if the folder in this plugin isn't used? Is it possible the local ones have precedence or are out of date? This issue is repeated several computers. Thanks for any insights you might have!

The specific error I'm getting from the websocket is: "lws_ssl_client_connect2 failed"

**Comment by feixuwu** [comment]
hi, I heard some people said the bug was exist on windows, and I have fixed and submit the problem.
the bug on windows is UE4 4.20's bug(I guess u upgraded the engine currently), the FPaths::FileExists function will get the wrong result on windows.
I have not tested on ios, so please pull the latest content, and to check if my demo project works on ios,
if it not works, please let me know.

**Comment by feixuwu** [comment]
hi, please update the latest content, it fixed the bug.
you don't need copy ca folder to your own content folder anymore,
the CA content is now in the code.

**Comment by kgriffiths** [comment]
Awesome, thanks a ton!
