### ISSUE TITLE
too large MAX_ECHO_PAYLOAD crashes the engine

### ISSUE THREAD

**Issue by tgrothm** [feixuwu/UEWebsocket#34]
If the value for `MAX_ECHO_PAYLOAD` is changed to accomodate large messages, the engine crashes at BeginPlay.

I moved the buffer declaration to the header:
```c++
unsigned char buf[MAX_ECHO_PAYLOAD] = {};
```

and changed the .cpp file to be:
```c++
while (mSendQueue.Num() > 0)
{
	std::string strData = TCHAR_TO_UTF8(*mSendQueue[0]);

	memcpy(&buf[LWS_PRE], strData.c_str(), strData.size() );
	lws_write(mlws, &buf[LWS_PRE], strData.size(), LWS_WRITE_TEXT);

	mSendQueue.RemoveAt(0);
}
```

After these changes the issue was resolved.

**Comment by feixuwu** [comment]
First, This is not the right way to fix the problem.
I did not test, but I guess the crash maybe the stack overflow(the stack object is too big), so you can change the stack variable(buf) to dynamic variable should fix the problem,
For example:
unsigned char* buf = new unsigned char[LWS_PRE + MAX_ECHO_PAYLOAD];
do remember delete []buf before the function return.

Your code change will cause memcpy stack overflow, It is critical dangerous!!
By the way, in my opinion, developer should not make logic depend on the max packet size,
developer should consider the situation the data may not be send in a single packet,
this is a usual case, you can not send a huge file to remote by a single udp or tcp packet.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: tgrothm <notifications@github.com>
发送时间: Wednesday, February 27, 2019 9:01:33 PM
收件人: feixuwu/UEWebsocket
抄送: Subscribed
主题: [feixuwu/UEWebsocket] too large MAX_ECHO_PAYLOAD crashes the engine (#34)


If the value for MAX_ECHO_PAYLOAD is changed to accomodate large messages, the engine crashes at BeginPlay.

I moved the bugger declaration to the header:

unsigned char buf[MAX_ECHO_PAYLOAD] = {};

and changed the .cpp file to be:

while (mSendQueue.Num() > 0)
{
        std::string strData = TCHAR_TO_UTF8(*mSendQueue[0]);

        memcpy(&buf[LWS_PRE], strData.c_str(), strData.size() );
        lws_write(mlws, &buf[LWS_PRE], strData.size(), LWS_WRITE_TEXT);

        mSendQueue.RemoveAt(0);
}

After these changes the issue was resolved.

―

**Comment by feixuwu** [comment]
change the buf to a heap object is slow a lot than the current stack object.
in most case, we do not need such a big MAX_ECHO_PAYLOAD, for people who really need big packet,
can change the buf to a  heap object, and delete the heap object before return.

**Comment by tgrothm** [comment]
The original local `unsigned char[LWS_PRE + MAX_ECHO_PAYLOAD]` is fast on stack but has limited size, of course.
Using `new` and `delete` on heap should work fine but would be slower.

Isn't declaring the array as a class member (so it lives on heap like the object does) the fastest version because it is initialised once and reused all the time? (checking the size before using memcpy)

**Comment by feixuwu** [comment]
the key point is you need alloc the buffer on heap,
so in this plugin, a member works,  you do not need alloc this buffer every time send.
