### ISSUE TITLE
How to tell if a value was included in the json message

### ISSUE THREAD

**Issue by TheTyrius** [feixuwu/UEWebsocket#48]
Unreal seems to initialize variables regardless. For example I'm trying to tell if a int/string field was included in the json. If I "get" the field in blueprints and "== 0" it's true both jsons where a value of 0 and no value for the field was supplied.

Any tip you know how to tell "null" values?

**Comment by feixuwu** [comment]
there's a function GetJsonIntField in the plugin, u can call it from blueprint,
this function only check int field, but u can create a function just check field exist.

**Comment by TheTyrius** [comment]
I guessed I had to check the json directly, because the types after jsontoobject can't have null-Values. Alright, thanks for the tip!

**Comment by feixuwu** [comment]
yes, u are right, u can create a blueprint function to check if the field exist.


________________________________
发件人: Philipp B <notifications@github.com>
发送时间: 2019年6月11日 10:18
收件人: feixuwu/UEWebsocket
抄送: xufeiwu; Comment
主题: Re: [feixuwu/UEWebsocket] How to tell if a value was included in the json message (#48)


I guessed I had to check the json directly, because the types after jsontoobject can't have null-Values. Alright, thanks for the tip!

―
