### ISSUE TITLE
4.23 fails to compile

### ISSUE THREAD

**Issue by rt974** [feixuwu/UEWebsocket#60]
Hi i've downloaded the 4.22 release and tried compiling on ue 4.23. fails miserably.

Also usually i can update easily from unreal versions to another using the "open a copy" option, but since 4.22 its impossible for me to upgrade my project, im stuck at 4.21.

Thats so boring i wanted to try that Chaos destruction stuff they added recently.

These visual studio errors are killing me.

**Comment by feixuwu** [comment]
hi, I will fix it this week, I have received some pr, I will check it ASAP.
获取 Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by feixuwu** [comment]
Hi, 4.23 is supported, please pull the latest content.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: rt974 <notifications@github.com>
发送时间: Wednesday, September 11, 2019 1:40:50 PM
收件人: feixuwu/UEWebsocket <UEWebsocket@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [feixuwu/UEWebsocket] 4.23 fails to compile (#60)


Hi i've downloaded the 4.22 release and tried compiling on ue 4.23. fails miserably.

Also usually i can update easily from unreal versions to another using the "open a copy" option, but since 4.22 its impossible for me to upgrade my project, im stuck at 4.21.

Thats so boring i wanted to try that Chaos destruction stuff they added recently.

These visual studio errors are killing me.

―

**Comment by rt974** [comment]
Hi,

It works now !
Thank you !
