### ISSUE TITLE
Fails to package 4.24.1 windows 64

### ISSUE THREAD

**Issue by masterofshapes** [feixuwu/UEWebsocket#73]
Works in editor but when try to package fails with error:

UATHelper: Packaging (Windows (64-bit)):     C:/PM/Plugins/WebSocket/Source/WebSocket/Public/WebSocket.h(5): fatal error C1083: Cannot open include file: 'ModuleManager.h': No such file or directory
UATHelper: Packaging (Windows (64-bit)): Took 7.0824944s to run UnrealBuildTool.exe, ExitCode=5

**Comment by robjmeza** [comment]
at first we couldn't open our project when we moved the plugins folder to our project.
so we used the binaries your UEWebSocket project creates when first opening and placed them into our project.
only after doing this did our project open with the WebSocket plugin.
and like masterofshapes states after trying to package the plugin will not build.

our project or a brand new project will not compile. 
this code is from a new project.
![error](https://user-images.githubusercontent.com/11287786/73131223-05af5680-3fbc-11ea-8b5b-71ca53ebab71.png)

i cleared up some errors but it always fails because it cannot open ModuleManger.h

**Comment by fabiomatsui-acn** [comment]
I'm new to Unreal, so keep that in mind...

I found two ways to work around this. In all my `.Target.cs` files I commented the following line.

`DefaultBuildSettings = BuildSettingsVersion.V2;`

Since new 4.24.1 projects add that automatically, I assume this is the new way forward. So probably the correct thing to do is correct all missing #includes like replacing:

`#include "Modules/ModuleManager.h"`
 with

`#include "Modules/ModuleManager.h"`

and 

`#include "PreWindowsApi.h"`

with

`#include "Windows/PreWindowsApi.h"`

**Comment by robjmeza** [comment]
thank you for responding before i really went down the road of trying to figure this out.
just tried your suggestions and worked first try on a new project.
so hopefully just works first try in our project.
thank you very much.

**Comment by Jungleboy76** [comment]
im a C++ noob but here what ive done ...
ive fixed this problem by setting the complete path to the missing modules.

for ModuleManager in Websocket.h:
#include "d:/Unreal-Engine/UE_4.24/Engine/Source/Runtime/Core/Public/Modules/ModuleManager.h"

and this for all missing includes...

i still get some errors but this compiles and work in editor / standalone.

i hope this helps a bit.

**Comment by masterofshapes** [comment]
That works thanks!
